# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/Mohammad Pervaiz/projects/loadbalancer"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/Mohammad Pervaiz/projects/loadbalancer"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Mohammad Pervaiz/projects/loadbalancer/CMakeFiles" "/mnt/c/Users/Mohammad Pervaiz/projects/loadbalancer//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Mohammad Pervaiz/projects/loadbalancer/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lb_lib

# Build rule for target.
lb_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lb_lib
.PHONY : lb_lib

# fast build rule for target.
lb_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/build
.PHONY : lb_lib/fast

#=============================================================================
# Target rules for targets named lb

# Build rule for target.
lb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lb
.PHONY : lb

# fast build rule for target.
lb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb.dir/build.make CMakeFiles/lb.dir/build
.PHONY : lb/fast

#=============================================================================
# Target rules for targets named test_routing

# Build rule for target.
test_routing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_routing
.PHONY : test_routing

# fast build rule for target.
test_routing/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_routing.dir/build.make tests/cpp/CMakeFiles/test_routing.dir/build
.PHONY : test_routing/fast

src/config/config.o: src/config/config.cpp.o
.PHONY : src/config/config.o

# target to build an object file
src/config/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/config/config.cpp.o
.PHONY : src/config/config.cpp.o

src/config/config.i: src/config/config.cpp.i
.PHONY : src/config/config.i

# target to preprocess a source file
src/config/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/config/config.cpp.i
.PHONY : src/config/config.cpp.i

src/config/config.s: src/config/config.cpp.s
.PHONY : src/config/config.s

# target to generate assembly for a file
src/config/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/config/config.cpp.s
.PHONY : src/config/config.cpp.s

src/core/backend_connector.o: src/core/backend_connector.cpp.o
.PHONY : src/core/backend_connector.o

# target to build an object file
src/core/backend_connector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/backend_connector.cpp.o
.PHONY : src/core/backend_connector.cpp.o

src/core/backend_connector.i: src/core/backend_connector.cpp.i
.PHONY : src/core/backend_connector.i

# target to preprocess a source file
src/core/backend_connector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/backend_connector.cpp.i
.PHONY : src/core/backend_connector.cpp.i

src/core/backend_connector.s: src/core/backend_connector.cpp.s
.PHONY : src/core/backend_connector.s

# target to generate assembly for a file
src/core/backend_connector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/backend_connector.cpp.s
.PHONY : src/core/backend_connector.cpp.s

src/core/backend_node.o: src/core/backend_node.cpp.o
.PHONY : src/core/backend_node.o

# target to build an object file
src/core/backend_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/backend_node.cpp.o
.PHONY : src/core/backend_node.cpp.o

src/core/backend_node.i: src/core/backend_node.cpp.i
.PHONY : src/core/backend_node.i

# target to preprocess a source file
src/core/backend_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/backend_node.cpp.i
.PHONY : src/core/backend_node.cpp.i

src/core/backend_node.s: src/core/backend_node.cpp.s
.PHONY : src/core/backend_node.s

# target to generate assembly for a file
src/core/backend_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/backend_node.cpp.s
.PHONY : src/core/backend_node.cpp.s

src/core/backend_pool.o: src/core/backend_pool.cpp.o
.PHONY : src/core/backend_pool.o

# target to build an object file
src/core/backend_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/backend_pool.cpp.o
.PHONY : src/core/backend_pool.cpp.o

src/core/backend_pool.i: src/core/backend_pool.cpp.i
.PHONY : src/core/backend_pool.i

# target to preprocess a source file
src/core/backend_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/backend_pool.cpp.i
.PHONY : src/core/backend_pool.cpp.i

src/core/backend_pool.s: src/core/backend_pool.cpp.s
.PHONY : src/core/backend_pool.s

# target to generate assembly for a file
src/core/backend_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/backend_pool.cpp.s
.PHONY : src/core/backend_pool.cpp.s

src/core/backpressure_manager.o: src/core/backpressure_manager.cpp.o
.PHONY : src/core/backpressure_manager.o

# target to build an object file
src/core/backpressure_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/backpressure_manager.cpp.o
.PHONY : src/core/backpressure_manager.cpp.o

src/core/backpressure_manager.i: src/core/backpressure_manager.cpp.i
.PHONY : src/core/backpressure_manager.i

# target to preprocess a source file
src/core/backpressure_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/backpressure_manager.cpp.i
.PHONY : src/core/backpressure_manager.cpp.i

src/core/backpressure_manager.s: src/core/backpressure_manager.cpp.s
.PHONY : src/core/backpressure_manager.s

# target to generate assembly for a file
src/core/backpressure_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/backpressure_manager.cpp.s
.PHONY : src/core/backpressure_manager.cpp.s

src/core/connection_manager.o: src/core/connection_manager.cpp.o
.PHONY : src/core/connection_manager.o

# target to build an object file
src/core/connection_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/connection_manager.cpp.o
.PHONY : src/core/connection_manager.cpp.o

src/core/connection_manager.i: src/core/connection_manager.cpp.i
.PHONY : src/core/connection_manager.i

# target to preprocess a source file
src/core/connection_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/connection_manager.cpp.i
.PHONY : src/core/connection_manager.cpp.i

src/core/connection_manager.s: src/core/connection_manager.cpp.s
.PHONY : src/core/connection_manager.s

# target to generate assembly for a file
src/core/connection_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/connection_manager.cpp.s
.PHONY : src/core/connection_manager.cpp.s

src/core/connection_pool.o: src/core/connection_pool.cpp.o
.PHONY : src/core/connection_pool.o

# target to build an object file
src/core/connection_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/connection_pool.cpp.o
.PHONY : src/core/connection_pool.cpp.o

src/core/connection_pool.i: src/core/connection_pool.cpp.i
.PHONY : src/core/connection_pool.i

# target to preprocess a source file
src/core/connection_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/connection_pool.cpp.i
.PHONY : src/core/connection_pool.cpp.i

src/core/connection_pool.s: src/core/connection_pool.cpp.s
.PHONY : src/core/connection_pool.s

# target to generate assembly for a file
src/core/connection_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/connection_pool.cpp.s
.PHONY : src/core/connection_pool.cpp.s

src/core/data_forwarder.o: src/core/data_forwarder.cpp.o
.PHONY : src/core/data_forwarder.o

# target to build an object file
src/core/data_forwarder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/data_forwarder.cpp.o
.PHONY : src/core/data_forwarder.cpp.o

src/core/data_forwarder.i: src/core/data_forwarder.cpp.i
.PHONY : src/core/data_forwarder.i

# target to preprocess a source file
src/core/data_forwarder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/data_forwarder.cpp.i
.PHONY : src/core/data_forwarder.cpp.i

src/core/data_forwarder.s: src/core/data_forwarder.cpp.s
.PHONY : src/core/data_forwarder.s

# target to generate assembly for a file
src/core/data_forwarder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/data_forwarder.cpp.s
.PHONY : src/core/data_forwarder.cpp.s

src/core/event_handlers.o: src/core/event_handlers.cpp.o
.PHONY : src/core/event_handlers.o

# target to build an object file
src/core/event_handlers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/event_handlers.cpp.o
.PHONY : src/core/event_handlers.cpp.o

src/core/event_handlers.i: src/core/event_handlers.cpp.i
.PHONY : src/core/event_handlers.i

# target to preprocess a source file
src/core/event_handlers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/event_handlers.cpp.i
.PHONY : src/core/event_handlers.cpp.i

src/core/event_handlers.s: src/core/event_handlers.cpp.s
.PHONY : src/core/event_handlers.s

# target to generate assembly for a file
src/core/event_handlers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/event_handlers.cpp.s
.PHONY : src/core/event_handlers.cpp.s

src/core/http_data_forwarder.o: src/core/http_data_forwarder.cpp.o
.PHONY : src/core/http_data_forwarder.o

# target to build an object file
src/core/http_data_forwarder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/http_data_forwarder.cpp.o
.PHONY : src/core/http_data_forwarder.cpp.o

src/core/http_data_forwarder.i: src/core/http_data_forwarder.cpp.i
.PHONY : src/core/http_data_forwarder.i

# target to preprocess a source file
src/core/http_data_forwarder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/http_data_forwarder.cpp.i
.PHONY : src/core/http_data_forwarder.cpp.i

src/core/http_data_forwarder.s: src/core/http_data_forwarder.cpp.s
.PHONY : src/core/http_data_forwarder.s

# target to generate assembly for a file
src/core/http_data_forwarder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/http_data_forwarder.cpp.s
.PHONY : src/core/http_data_forwarder.cpp.s

src/core/load_balancer.o: src/core/load_balancer.cpp.o
.PHONY : src/core/load_balancer.o

# target to build an object file
src/core/load_balancer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/load_balancer.cpp.o
.PHONY : src/core/load_balancer.cpp.o

src/core/load_balancer.i: src/core/load_balancer.cpp.i
.PHONY : src/core/load_balancer.i

# target to preprocess a source file
src/core/load_balancer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/load_balancer.cpp.i
.PHONY : src/core/load_balancer.cpp.i

src/core/load_balancer.s: src/core/load_balancer.cpp.s
.PHONY : src/core/load_balancer.s

# target to generate assembly for a file
src/core/load_balancer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/load_balancer.cpp.s
.PHONY : src/core/load_balancer.cpp.s

src/core/retry_handler.o: src/core/retry_handler.cpp.o
.PHONY : src/core/retry_handler.o

# target to build an object file
src/core/retry_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/retry_handler.cpp.o
.PHONY : src/core/retry_handler.cpp.o

src/core/retry_handler.i: src/core/retry_handler.cpp.i
.PHONY : src/core/retry_handler.i

# target to preprocess a source file
src/core/retry_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/retry_handler.cpp.i
.PHONY : src/core/retry_handler.cpp.i

src/core/retry_handler.s: src/core/retry_handler.cpp.s
.PHONY : src/core/retry_handler.s

# target to generate assembly for a file
src/core/retry_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/retry_handler.cpp.s
.PHONY : src/core/retry_handler.cpp.s

src/core/session_manager.o: src/core/session_manager.cpp.o
.PHONY : src/core/session_manager.o

# target to build an object file
src/core/session_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/session_manager.cpp.o
.PHONY : src/core/session_manager.cpp.o

src/core/session_manager.i: src/core/session_manager.cpp.i
.PHONY : src/core/session_manager.i

# target to preprocess a source file
src/core/session_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/session_manager.cpp.i
.PHONY : src/core/session_manager.cpp.i

src/core/session_manager.s: src/core/session_manager.cpp.s
.PHONY : src/core/session_manager.s

# target to generate assembly for a file
src/core/session_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/session_manager.cpp.s
.PHONY : src/core/session_manager.cpp.s

src/core/splice_forwarder.o: src/core/splice_forwarder.cpp.o
.PHONY : src/core/splice_forwarder.o

# target to build an object file
src/core/splice_forwarder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/splice_forwarder.cpp.o
.PHONY : src/core/splice_forwarder.cpp.o

src/core/splice_forwarder.i: src/core/splice_forwarder.cpp.i
.PHONY : src/core/splice_forwarder.i

# target to preprocess a source file
src/core/splice_forwarder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/splice_forwarder.cpp.i
.PHONY : src/core/splice_forwarder.cpp.i

src/core/splice_forwarder.s: src/core/splice_forwarder.cpp.s
.PHONY : src/core/splice_forwarder.s

# target to generate assembly for a file
src/core/splice_forwarder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/core/splice_forwarder.cpp.s
.PHONY : src/core/splice_forwarder.cpp.s

src/health/health_checker.o: src/health/health_checker.cpp.o
.PHONY : src/health/health_checker.o

# target to build an object file
src/health/health_checker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/health/health_checker.cpp.o
.PHONY : src/health/health_checker.cpp.o

src/health/health_checker.i: src/health/health_checker.cpp.i
.PHONY : src/health/health_checker.i

# target to preprocess a source file
src/health/health_checker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/health/health_checker.cpp.i
.PHONY : src/health/health_checker.cpp.i

src/health/health_checker.s: src/health/health_checker.cpp.s
.PHONY : src/health/health_checker.s

# target to generate assembly for a file
src/health/health_checker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/health/health_checker.cpp.s
.PHONY : src/health/health_checker.cpp.s

src/http/http_handler.o: src/http/http_handler.cpp.o
.PHONY : src/http/http_handler.o

# target to build an object file
src/http/http_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/http/http_handler.cpp.o
.PHONY : src/http/http_handler.cpp.o

src/http/http_handler.i: src/http/http_handler.cpp.i
.PHONY : src/http/http_handler.i

# target to preprocess a source file
src/http/http_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/http/http_handler.cpp.i
.PHONY : src/http/http_handler.cpp.i

src/http/http_handler.s: src/http/http_handler.cpp.s
.PHONY : src/http/http_handler.s

# target to generate assembly for a file
src/http/http_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/http/http_handler.cpp.s
.PHONY : src/http/http_handler.cpp.s

src/http/http_request.o: src/http/http_request.cpp.o
.PHONY : src/http/http_request.o

# target to build an object file
src/http/http_request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/http/http_request.cpp.o
.PHONY : src/http/http_request.cpp.o

src/http/http_request.i: src/http/http_request.cpp.i
.PHONY : src/http/http_request.i

# target to preprocess a source file
src/http/http_request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/http/http_request.cpp.i
.PHONY : src/http/http_request.cpp.i

src/http/http_request.s: src/http/http_request.cpp.s
.PHONY : src/http/http_request.s

# target to generate assembly for a file
src/http/http_request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/http/http_request.cpp.s
.PHONY : src/http/http_request.cpp.s

src/http/http_response.o: src/http/http_response.cpp.o
.PHONY : src/http/http_response.o

# target to build an object file
src/http/http_response.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/http/http_response.cpp.o
.PHONY : src/http/http_response.cpp.o

src/http/http_response.i: src/http/http_response.cpp.i
.PHONY : src/http/http_response.i

# target to preprocess a source file
src/http/http_response.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/http/http_response.cpp.i
.PHONY : src/http/http_response.cpp.i

src/http/http_response.s: src/http/http_response.cpp.s
.PHONY : src/http/http_response.s

# target to generate assembly for a file
src/http/http_response.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/http/http_response.cpp.s
.PHONY : src/http/http_response.cpp.s

src/http/http_response_parser.o: src/http/http_response_parser.cpp.o
.PHONY : src/http/http_response_parser.o

# target to build an object file
src/http/http_response_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/http/http_response_parser.cpp.o
.PHONY : src/http/http_response_parser.cpp.o

src/http/http_response_parser.i: src/http/http_response_parser.cpp.i
.PHONY : src/http/http_response_parser.i

# target to preprocess a source file
src/http/http_response_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/http/http_response_parser.cpp.i
.PHONY : src/http/http_response_parser.cpp.i

src/http/http_response_parser.s: src/http/http_response_parser.cpp.s
.PHONY : src/http/http_response_parser.s

# target to generate assembly for a file
src/http/http_response_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/http/http_response_parser.cpp.s
.PHONY : src/http/http_response_parser.cpp.s

src/logging/access_logger.o: src/logging/access_logger.cpp.o
.PHONY : src/logging/access_logger.o

# target to build an object file
src/logging/access_logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/logging/access_logger.cpp.o
.PHONY : src/logging/access_logger.cpp.o

src/logging/access_logger.i: src/logging/access_logger.cpp.i
.PHONY : src/logging/access_logger.i

# target to preprocess a source file
src/logging/access_logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/logging/access_logger.cpp.i
.PHONY : src/logging/access_logger.cpp.i

src/logging/access_logger.s: src/logging/access_logger.cpp.s
.PHONY : src/logging/access_logger.s

# target to generate assembly for a file
src/logging/access_logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/logging/access_logger.cpp.s
.PHONY : src/logging/access_logger.cpp.s

src/logging/logger.o: src/logging/logger.cpp.o
.PHONY : src/logging/logger.o

# target to build an object file
src/logging/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/logging/logger.cpp.o
.PHONY : src/logging/logger.cpp.o

src/logging/logger.i: src/logging/logger.cpp.i
.PHONY : src/logging/logger.i

# target to preprocess a source file
src/logging/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/logging/logger.cpp.i
.PHONY : src/logging/logger.cpp.i

src/logging/logger.s: src/logging/logger.cpp.s
.PHONY : src/logging/logger.s

# target to generate assembly for a file
src/logging/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/logging/logger.cpp.s
.PHONY : src/logging/logger.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb.dir/build.make CMakeFiles/lb.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb.dir/build.make CMakeFiles/lb.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb.dir/build.make CMakeFiles/lb.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/metrics/metrics.o: src/metrics/metrics.cpp.o
.PHONY : src/metrics/metrics.o

# target to build an object file
src/metrics/metrics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/metrics/metrics.cpp.o
.PHONY : src/metrics/metrics.cpp.o

src/metrics/metrics.i: src/metrics/metrics.cpp.i
.PHONY : src/metrics/metrics.i

# target to preprocess a source file
src/metrics/metrics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/metrics/metrics.cpp.i
.PHONY : src/metrics/metrics.cpp.i

src/metrics/metrics.s: src/metrics/metrics.cpp.s
.PHONY : src/metrics/metrics.s

# target to generate assembly for a file
src/metrics/metrics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/metrics/metrics.cpp.s
.PHONY : src/metrics/metrics.cpp.s

src/metrics/metrics_server.o: src/metrics/metrics_server.cpp.o
.PHONY : src/metrics/metrics_server.o

# target to build an object file
src/metrics/metrics_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/metrics/metrics_server.cpp.o
.PHONY : src/metrics/metrics_server.cpp.o

src/metrics/metrics_server.i: src/metrics/metrics_server.cpp.i
.PHONY : src/metrics/metrics_server.i

# target to preprocess a source file
src/metrics/metrics_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/metrics/metrics_server.cpp.i
.PHONY : src/metrics/metrics_server.cpp.i

src/metrics/metrics_server.s: src/metrics/metrics_server.cpp.s
.PHONY : src/metrics/metrics_server.s

# target to generate assembly for a file
src/metrics/metrics_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/metrics/metrics_server.cpp.s
.PHONY : src/metrics/metrics_server.cpp.s

src/net/connection.o: src/net/connection.cpp.o
.PHONY : src/net/connection.o

# target to build an object file
src/net/connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/net/connection.cpp.o
.PHONY : src/net/connection.cpp.o

src/net/connection.i: src/net/connection.cpp.i
.PHONY : src/net/connection.i

# target to preprocess a source file
src/net/connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/net/connection.cpp.i
.PHONY : src/net/connection.cpp.i

src/net/connection.s: src/net/connection.cpp.s
.PHONY : src/net/connection.s

# target to generate assembly for a file
src/net/connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/net/connection.cpp.s
.PHONY : src/net/connection.cpp.s

src/net/epoll_reactor.o: src/net/epoll_reactor.cpp.o
.PHONY : src/net/epoll_reactor.o

# target to build an object file
src/net/epoll_reactor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/net/epoll_reactor.cpp.o
.PHONY : src/net/epoll_reactor.cpp.o

src/net/epoll_reactor.i: src/net/epoll_reactor.cpp.i
.PHONY : src/net/epoll_reactor.i

# target to preprocess a source file
src/net/epoll_reactor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/net/epoll_reactor.cpp.i
.PHONY : src/net/epoll_reactor.cpp.i

src/net/epoll_reactor.s: src/net/epoll_reactor.cpp.s
.PHONY : src/net/epoll_reactor.s

# target to generate assembly for a file
src/net/epoll_reactor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/net/epoll_reactor.cpp.s
.PHONY : src/net/epoll_reactor.cpp.s

src/net/tcp_listener.o: src/net/tcp_listener.cpp.o
.PHONY : src/net/tcp_listener.o

# target to build an object file
src/net/tcp_listener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/net/tcp_listener.cpp.o
.PHONY : src/net/tcp_listener.cpp.o

src/net/tcp_listener.i: src/net/tcp_listener.cpp.i
.PHONY : src/net/tcp_listener.i

# target to preprocess a source file
src/net/tcp_listener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/net/tcp_listener.cpp.i
.PHONY : src/net/tcp_listener.cpp.i

src/net/tcp_listener.s: src/net/tcp_listener.cpp.s
.PHONY : src/net/tcp_listener.s

# target to generate assembly for a file
src/net/tcp_listener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/net/tcp_listener.cpp.s
.PHONY : src/net/tcp_listener.cpp.s

src/tls/tls_context.o: src/tls/tls_context.cpp.o
.PHONY : src/tls/tls_context.o

# target to build an object file
src/tls/tls_context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/tls/tls_context.cpp.o
.PHONY : src/tls/tls_context.cpp.o

src/tls/tls_context.i: src/tls/tls_context.cpp.i
.PHONY : src/tls/tls_context.i

# target to preprocess a source file
src/tls/tls_context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/tls/tls_context.cpp.i
.PHONY : src/tls/tls_context.cpp.i

src/tls/tls_context.s: src/tls/tls_context.cpp.s
.PHONY : src/tls/tls_context.s

# target to generate assembly for a file
src/tls/tls_context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lb_lib.dir/build.make CMakeFiles/lb_lib.dir/src/tls/tls_context.cpp.s
.PHONY : src/tls/tls_context.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... lb"
	@echo "... lb_lib"
	@echo "... test_routing"
	@echo "... src/config/config.o"
	@echo "... src/config/config.i"
	@echo "... src/config/config.s"
	@echo "... src/core/backend_connector.o"
	@echo "... src/core/backend_connector.i"
	@echo "... src/core/backend_connector.s"
	@echo "... src/core/backend_node.o"
	@echo "... src/core/backend_node.i"
	@echo "... src/core/backend_node.s"
	@echo "... src/core/backend_pool.o"
	@echo "... src/core/backend_pool.i"
	@echo "... src/core/backend_pool.s"
	@echo "... src/core/backpressure_manager.o"
	@echo "... src/core/backpressure_manager.i"
	@echo "... src/core/backpressure_manager.s"
	@echo "... src/core/connection_manager.o"
	@echo "... src/core/connection_manager.i"
	@echo "... src/core/connection_manager.s"
	@echo "... src/core/connection_pool.o"
	@echo "... src/core/connection_pool.i"
	@echo "... src/core/connection_pool.s"
	@echo "... src/core/data_forwarder.o"
	@echo "... src/core/data_forwarder.i"
	@echo "... src/core/data_forwarder.s"
	@echo "... src/core/event_handlers.o"
	@echo "... src/core/event_handlers.i"
	@echo "... src/core/event_handlers.s"
	@echo "... src/core/http_data_forwarder.o"
	@echo "... src/core/http_data_forwarder.i"
	@echo "... src/core/http_data_forwarder.s"
	@echo "... src/core/load_balancer.o"
	@echo "... src/core/load_balancer.i"
	@echo "... src/core/load_balancer.s"
	@echo "... src/core/retry_handler.o"
	@echo "... src/core/retry_handler.i"
	@echo "... src/core/retry_handler.s"
	@echo "... src/core/session_manager.o"
	@echo "... src/core/session_manager.i"
	@echo "... src/core/session_manager.s"
	@echo "... src/core/splice_forwarder.o"
	@echo "... src/core/splice_forwarder.i"
	@echo "... src/core/splice_forwarder.s"
	@echo "... src/health/health_checker.o"
	@echo "... src/health/health_checker.i"
	@echo "... src/health/health_checker.s"
	@echo "... src/http/http_handler.o"
	@echo "... src/http/http_handler.i"
	@echo "... src/http/http_handler.s"
	@echo "... src/http/http_request.o"
	@echo "... src/http/http_request.i"
	@echo "... src/http/http_request.s"
	@echo "... src/http/http_response.o"
	@echo "... src/http/http_response.i"
	@echo "... src/http/http_response.s"
	@echo "... src/http/http_response_parser.o"
	@echo "... src/http/http_response_parser.i"
	@echo "... src/http/http_response_parser.s"
	@echo "... src/logging/access_logger.o"
	@echo "... src/logging/access_logger.i"
	@echo "... src/logging/access_logger.s"
	@echo "... src/logging/logger.o"
	@echo "... src/logging/logger.i"
	@echo "... src/logging/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/metrics/metrics.o"
	@echo "... src/metrics/metrics.i"
	@echo "... src/metrics/metrics.s"
	@echo "... src/metrics/metrics_server.o"
	@echo "... src/metrics/metrics_server.i"
	@echo "... src/metrics/metrics_server.s"
	@echo "... src/net/connection.o"
	@echo "... src/net/connection.i"
	@echo "... src/net/connection.s"
	@echo "... src/net/epoll_reactor.o"
	@echo "... src/net/epoll_reactor.i"
	@echo "... src/net/epoll_reactor.s"
	@echo "... src/net/tcp_listener.o"
	@echo "... src/net/tcp_listener.i"
	@echo "... src/net/tcp_listener.s"
	@echo "... src/tls/tls_context.o"
	@echo "... src/tls/tls_context.i"
	@echo "... src/tls/tls_context.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

